// The Edit furniture switch: furniture is locked until it is on. Checks that a drag on a piece spins the view instead of moving it,
// that a tap selects nothing, that Edit furniture unlocks dragging, that Done editing locks it again, and that the button clears the joystick.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const HERE=path.dirname(fileURLToPath(import.meta.url)), ROOT=path.resolve(HERE,'..'), OUT=path.join(HERE,'out');
const APP=path.join(ROOT,'src','app.html'), THREE=path.join(HERE,'vendor','three-r128.min.js');
const { chromium } = await import(process.env.PLAYWRIGHT || 'playwright');
fs.mkdirSync(OUT,{recursive:true}); process.chdir(OUT); for(const d of ['tex','models']) try{ fs.symlinkSync('../../'+d, d); }catch(e){} // the scanned textures and models, beside the wrapped pages
let body=fs.readFileSync(APP,'utf8');
body=body.replace('requestAnimationFrame(loop);\n})();', `window.__t={eval:c=>eval(c)};\nrequestAnimationFrame(loop);\n})();`);
fs.writeFileSync('wrapped_edit.html', `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}[hidden]{display:none!important}</style></head><body>${body}</body></html>`);
const browser=await chromium.launch({ executablePath:process.env.CHROMIUM||undefined, args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--allow-file-access-from-files'] });
const page=await (await browser.newContext({ viewport:{width:900,height:700}, deviceScaleFactor:1 })).newPage();
const errs=[]; page.on('pageerror', e=>errs.push('PAGEERR '+e.message)); page.on('console', m=>{ if(m.type()==='error') errs.push(m.text()); });
await page.route('**/three.min.js', r=>r.fulfill({body:fs.readFileSync(THREE), contentType:'application/javascript'}));
await page.route('https://fonts.googleapis.com/**', r=>r.fulfill({body:'', contentType:'text/css'}));
await page.goto('file://'+process.cwd()+'/wrapped_edit.html'); await page.evaluate(()=>{ localStorage.clear(); sessionStorage.clear(); localStorage.setItem('theater113-help-seen','1'); localStorage.setItem('tuhaye-focus','theater'); localStorage.setItem('theater113-quality','fast'); }); await page.reload();
await page.waitForFunction(()=>window.__t, null, {timeout:120000}); await page.waitForTimeout(1500);
const E=c=>page.evaluate(c=>__t.eval(c), c);
let fails=0; const ok=(n,c,i)=>{ console.log((c?'ok   ':'FAIL ')+n+(i!==undefined?' '+JSON.stringify(i):'')); if(!c) fails++; };
const snap=async()=>JSON.parse(await E(`JSON.stringify(items().map(i=>[i.id,i.x,i.z]))`));
const diff=(a,b)=>a.filter((r,k)=>Math.hypot(r[1]-b[k][1],r[2]-b[k][2])>1e-6).map(r=>r[0]);
const piece=async()=>JSON.parse(await E(`Object.assign(orbit,OG); applyCamera(); const it=items().find(i=>i.type==='tallfridge'); _v.set(it.x,baseY(it)+it.h*.6,it.z).project(camera); const r=canvas.getBoundingClientRect(); JSON.stringify({id:it.id,x:it.x,z:it.z,sx:r.left+(_v.x+1)/2*r.width,sy:r.top+(1-_v.y)/2*r.height,theta:OG.theta,sel:selId})`));
const drag=async(p,dx,dy)=>{ await page.mouse.move(p.sx,p.sy); await page.mouse.down(); for(let i=1;i<=10;i++) await page.mouse.move(p.sx+dx*i/10,p.sy+dy*i/10); await page.mouse.up(); await page.waitForTimeout(400); };
ok('starts locked', await E(`!EDIT && document.querySelector('#editTxt').textContent==='Edit furniture'`));
let s0=await snap(), p0=await piece(); await drag(p0,80,0); let p1=await piece();
ok('locked: drag on a piece moves nothing', diff(await snap(),s0).length===0, diff(await snap(),s0));
ok('locked: the drag spun the view instead', Math.abs(p1.theta-p0.theta)>.05, {theta:[p0.theta,p1.theta]});
await page.mouse.click(p1.sx,p1.sy); await page.waitForTimeout(400);
ok('locked: tapping a piece selects nothing', await E('selId===null'));
ok('locked: tap explains how to unlock', (await page.textContent('#toast')).includes('Edit furniture'));
await page.click('#editBtn'); await page.waitForTimeout(300);
ok('Edit furniture turns editing on', await E(`EDIT && document.querySelector('#editTxt').textContent==='Done editing'`));
s0=await snap(); p0=await piece(); await drag(p0,-60,0); p1=await piece();
ok('editing: drag moves the piece under the pointer', diff(await snap(),s0).length===1, {moved:diff(await snap(),s0), sel:await E('selId')});
await page.click('#editBtn'); await page.waitForTimeout(300);
ok('Done editing locks again and deselects', await E('!EDIT && selId===null'));
await page.click('#tAdd'); await page.waitForTimeout(300);
ok('Add unlocks editing', await E(`EDIT && !document.querySelector('#sAdd').hidden`));
await page.click('#sAdd [data-act=close]'); await page.click('#editBtn'); await page.waitForTimeout(200);
await page.click('#views button[data-mode=walk]'); await page.waitForTimeout(800);
const box=await page.evaluate(()=>{ const r=e=>document.querySelector(e).getBoundingClientRect(); const a=r('#editBtn'), b=r('#joy'), c=r('#sitBtn'); const hit=(p,q)=>p.left<q.right&&p.right>q.left&&p.top<q.bottom&&p.bottom>q.top; return {joy:hit(a,b), sit:hit(a,c), visible:a.width>0}; });
ok('walk: the button clears the joystick and Sit down', box.visible&&!box.joy&&!box.sit, box);
console.log(errs.slice(0,10).join('\n')||'no errors'); console.log(fails?`${fails} FAILED`:'ALL OK'); await browser.close();
